apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: axtacr.azurecr.io/echo-springboot:1.0.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Always