name: Deploy Docker Image
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        required: true

jobs:
  get_tags:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - run: echo "hi"
