name: Deploy Docker Image
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        required: true
        description: yes
        options:
          - DEV
          - QA
          - PROD
      environment:
        type: environment
        description: Select the environment
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3