name: Deploy Docker Image
on:
  workflow_dispatch:
      environment:
        type: environment
        description: Select the environment
        required: true
      tags:
        description: "The tags"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
    - uses: actions/checkout@v3