name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "helm_chart"
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: axtacr
        # Container registry password
        password: ${{ secrets.ACR_PW }}
        # Container registry server url
        login-server: axtacr.azurecr.io

    - name: Build & Push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: axtacr.azurecr.io/echo-springboot:1.3.0

    - name: Update Version
      run: |
          version=$(cat ./helm_chart/values.yaml | grep tag: | awk '{print $2}')
          sed -i "s/$version/1.3.0/" ./helm_chart/values.yaml

    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v0.3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        commit_message: Version updated
