name: Build and Push Docker Image

on:
  push:
    branches: [ 
                "master",
                "release-candidates",
                "develop"
              ]
    paths-ignore:
      - "helm_chart"
  pull_request:
    branches: [ 
                "master",
                "release-candidates",
                "develop"
              ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: axtacr
        # Container registry password
        password: ${{ secrets.ACR_PW }}
        # Container registry server url
        login-server: axtacr.azurecr.io

    - name: Perform semantic-release
      uses: codfish/semantic-release-action@v1
      with:
        branches: |
          [
            'master',
            {
              name: 'release-candidates',
              prerelease: 'rc'
            }
          ]
        plugins: |
          ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/npm', '@semantic-release/github']
        tag_format: "${version}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: echo $NEW_RELEASE_PUBLISHED

    - name: Build & Push
      uses: docker/build-push-action@v2
      if: env.NEW_RELEASE_PUBLISHED == 'true'
      with:
        push: true
        tags: axtacr.azurecr.io/echo-springboot:${{ env.RELEASE_VERSION }}

    - name: Update Version
      if: env.NEW_RELEASE_PUBLISHED == 'true'
      run: |
          version=$(cat ./helm_chart/values.yaml | grep tag: | awk '{print $2}')
          sed -i "s/$version/${{ env.RELEASE_VERSION }}/" ./helm_chart/values.yaml

    - name: Commit and push changes
      if: env.NEW_RELEASE_PUBLISHED == 'true'
      uses: devops-infra/action-commit-push@v0.3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        commit_message: "chore: updated helm image tag to ${{ env.RELEASE_VERSION }}"
